/**
 * WASM bridge — loads and initializes the strepitus-core WASM module.
 * Provides typed access to the Rust physics engine.
 */

// The wasm-pack output will be in src/wasm/ after building
// Types are generated by wasm-bindgen
type WasmModule = typeof import("../wasm/strepitus_core");

let wasmModule: WasmModule | null = null;

export async function initWasm(): Promise<WasmModule> {
  if (wasmModule) return wasmModule;

  try {
    // Dynamic import of the wasm-pack generated module
    const module = await import("../wasm/strepitus_core");
    await module.default();
    wasmModule = module;
    console.log(
      `[strepitus] WASM loaded — physics engine v${module.version()}`
    );
    return module;
  } catch (err) {
    console.error("[strepitus] Failed to load WASM module:", err);
    throw err;
  }
}

export function getWasm(): WasmModule {
  if (!wasmModule) {
    throw new Error("WASM module not initialized. Call initWasm() first.");
  }
  return wasmModule;
}
